import logging
import os
import json
from kiteconnect import KiteConnect
from datetime import datetime, timedelta
import pandas as pd
api_key = ''
secret = ''

# Set up logging
# logging.basicConfig(level=logging.DEBUG)

kite = KiteConnect(api_key=api_key)

TOKEN_FILE = "access_token.json"

def save_access_token(token):
    with open(TOKEN_FILE, 'w') as f:
        json.dump({"access_token": token}, f)

def load_access_token():
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, 'r') as f:
            data = json.load(f)
            return data.get("access_token")
    return None


def authenticate():
    access_token = load_access_token()
    if access_token:
        kite.set_access_token(access_token)
        try:
            kite.margins() 
        except Exception as e:
            logging.warning("Access token may be invalid, re-authenticating...")
            return get_access_token() 
    else:
        return get_access_token()

def get_access_token():
    print("Go to the following URL to authorize:")
    print(kite.login_url())
    request_token = input("Enter the request token: ")
    data = kite.generate_session(request_token, api_secret=secret)
    kite.set_access_token(data["access_token"])
    save_access_token(data["access_token"])
  

def print_account_balance():
    try:
        margins = kite.margins()
        available_balance = margins['equity']['available']['cash']
        print(f"Your available balance is: {available_balance}")
    except Exception as e:
        logging.error(f"Error fetching account balance: {e}")

# Authenticate and print the account balance
authenticate()


# Define the symbol and timeframe
# symbol = "SKIPPER"
# exchange = "NSE"  # Or "BSE" depending on the exchange

# Set the interval to '1minute' (1m), '5minute' (5m), etc.
interval = "day"  # You can use '5minute', '15minute', etc.
# to_date = datetime.now()

#symbols = ['TCS']
symbols = ['ICICIBANK', 'LICI', 'HDFCBANK', 'RELIANCE', 'ITC', 'TCS', 'HINDUNILVR', 'SBIN', 'INFY', 'BHARTIARTL', 'BAJFINANCE', 'HCLTECH', 'TITAN', 'LT', 'KOTAKBANK', 'ASIANPAINT', 'ADANIENT', 'MARUTI', 'AXISBANK', 'ULTRACEMCO', 'SUNPHARMA', 'BAJAJFINSV', 'TATAMOTORS', 'NTPC', 'DMART', 'ONGC', 'NESTLEIND', 'ADANIGREEN', 'WIPRO', 'COALINDIA', 'ADANIPORTS', 'POWERGRID', 'M_M', 'ADANIPOWER', 'BAJAJ_AUTO', 'JSWSTEEL', 'LTIM', 'IOC', 'HAL', 'DLF', 'VBL', 'TATASTEEL', 'SBILIFE', 'SIEMENS', 'JIOFIN', 'HINDALCO', 'GRASIM', 'HDFCLIFE', 'PIDILITIND', 'BEL', 'IRFC', 'HINDZINC', 'INDUSINDBK', 'BRITANNIA', 'PFC', 'BANKBARODA', 'GODREJCP', 'ADANIENSOL', 'TECHM', 'INDIGO', 'ATGL', 'RECLTD', 'EICHERMOT', 'TRENT', 'ZOMATO', 'GAIL', 'CHOLAFIN', 'PNB', 'TATAPOWER', 'DIVISLAB', 'TATACONSUM', 'AMBUJACEM', 'CIPLA', 'DABUR', 'ABB', 'LODHA', 'SHREECEM', 'DRREDDY', 'BPCL', 'TVSMOTOR', 'UNIONBANK', 'VEDL', 'HAVELLS', 'BAJAJHLDNG', 'HEROMOTOCO', 'POLYCAB', 'APOLLOHOSP', 'IOB', 'MANKIND', 'CANBK', 'TORNTPHARM', 'IDEA', 'SHRIRAMFIN', 'ICICIPRULI', 'SBICARD', 'JINDALSTEL', 'SRF', 'IDBI', 'IRCTC', 'MARICO', 'BERGEPAINT', 'ICICIGI', 'CGPOWER', 'ZYDUSLIFE', 'MOTHERSON', 'HDFCAMC', 'BHEL', 'TIINDIA', 'COLPAL', 'NAUKRI', 'MAXHEALTH', 'NHPC', 'JSWENERGY', 'BOSCHLTD', 'AUROPHARMA', 'IDFCFIRSTB', 
'INDHOTEL', 'ALKEM', 'YESBANK', 'NMDC', 'SOLARINDS', 'MUTHOOTFIN', 'LUPIN', 'SUPREMEIND', 'BHARATFORG', 'PATANJALI', 'INDIANB', 'PERSISTENT', 'HINDPETRO', 'PGHH', 'LTTS', 'GODREJPROP', 'TATAELXSI', 'MRF', 'CUMMINSIND', 'INDUSTOWER', 'PIIND', 'ASHOKLEY', 
'GICRE', 'FACT', 'AUBANK', 'CONCOR', 'OBEROIRLTY', 'SUZLON', 'MPHASIS', 'ASTRAL', 'BANKINDIA', 'SAIL', 'TATACOMM', 'SCHAEFFLER', 'NYKAA', 'GMRINFRA', 'BALKRISIND', 'LINDEINDIA', 'TATATECH', 'UCOBANK', 'UBL', 'PRESTIGE', 'JSL', 'AWL', 'JSWINFRA', 'UPL', 'CENTRALBK', 'TORNTPOWER', 'MAZDOCK', 'ABCAPITAL', 'PAGEIND', 'APLAPOLLO', 'DALBHARAT', 'KPITTECH', '3MINDIA', 'OIL', 'FLUOROCHEM', 'ACC', 'PAYTM', 'PHOENIXLTD', 'UNOMINDA', 'DIXON', 'COFORGE', 'BANDHANBNK', 'RVNL', 'FEDERALBNK', 'SUNDARMFIN', 'SONACOMS', 'JUBLFOOD', 'COROMANDEL', 'THERMAX', 'OFSS', 'POLICYBZR', 'SJVN', 'NLCINDIA', 'NIACL', 'AIAENG', 'M_MFIN', 'DEEPAKNTR', 'KALYANKJIL', 'METROBRAND', 'POONAWALLA', 'PETRONET', 'ESCORTS', 'MFSL', 'VOLTAS', 'HONAUT', 'GLAXO', 'MAHABANK', 'CRISIL', 'GUJGASLTD', 'GLAND', 'FORTIS', 'MANYAVAR', 'STARHEALTH', 'ZFCVINDIA', 'BDL', 'LICHSGFIN', 'BIOCON', 'LLOYDSME', 'BSE', 'KEI', 'IGL', 'PSB', 'JKCEMENT', 'ANGELONE', 'SYNGENE', 'APOLLOTYRE', 'DELHIVERY', 'IPCALAB', 'ITI', 'KPRMILL', 'IREDA', 'TATACHEM', 'NAM_INDIA', 'SUNTV', 'ENDURANCE', 'MSUMI', 'AJANTPHARM', 'EXIDEIND', 'KANSAINER', 'HINDCOPPER', 'ZEEL', 'GRINDWELL', 'SUNDRMFAST', 'MEDANTA', '360ONE', 'CREDITACC', 'HATSUN', 'HUDCO', 'CYIENT', 'JBCHEPHARM', 'GODREJIND', 'EMAMILTD', 'IRB', 'NH', 'TIMKEN', 'APARINDS', 'NATIONALUM', 'RAMCOCEM', 'RATNAMANI', 'GLENMARK', 'AARTIIND', 'MRPL', 'DEVYANI', 'ISEC', 'IIFL', 'LAURUSLABS', 'SKFINDIA', 'RELAXO', 'KIOCL', 'POWERINDIA', 'RADICO', 'TATAINVEST', 'FIVESTAR', 'LALPATHLAB', 'BATAINDIA', 'ABFRL', 'CARBORUNIV', 'GILLETTE', 'ATUL', 'PEL', 'SONATSOFTW', 'ASTERDM', 'KAJARIACER', 'BRIGADE', 'IDFC', 'PNBHOUSING', 'SUMICHEM', 'CROMPTON', 'CHOLAHLDNG', 'BSOFT', 'PFIZER', 'BLUESTARCO', 'CDSL', 'NAVINFLUOR', 'SANOFI', 'SUVENPHAR', 'MOTILALOFS', 'TRIDENT', 'AFFLE', 'PPLPHARMA', 'VINATIORGA', 'CIEINDIA', 'TTML', 'COCHINSHIP', 'RRKABEL', 'CASTROLIND', 'JYOTHYLAB', 'CESC', 'BLUEDART', 'WHIRLPOOL', 'JBMA', 'CENTURYPLY', 'ELGIEQUIP', 'GSPL', 'KAYNES', 'RBLBANK', 'CELLO', 'RHIM', 'CLEAN', 'FINCABLES', 'IRCON', 'INDIAMART', 'PVRINOX', 'APTUS', 'DCMSHRIRAM', 'INOXWIND', 'CGCL', 'KIMS', 'TVSHLTD', 'CHAMBLFERT', 'SHYAMMETL', 'EIHOTEL', 'CONCORDBIO', 'NSLNISP', 'FINEORG', 'APLLTD', 'IEX', 'TEJASNET', 'NBCC', 'TANLA', 'NATCOPHARM', 'KEC', 'MANAPPURAM', 'WELCORP', 'POLYMED', 'CHALET', 'TITAGARH', 'HONASA', 'GESHIP', 'ARE_M', 'WELSPUNLIV', 'ASAHIINDIA', 'REDINGTON', 'ZENSARTECH', 'ASTRAZEN', 'NUVOCO', 'BIKAJI', 'HAPPSTMNDS', 'KARURVYSYA', 'HSCL', 'J_KBANK', 'ABSLAMC', 'SFL', 'SWANENERGY', 'TRITURBINE', 'BASF', 'JINDALSAW', 'RKFORGE', 'JWL', 'BLS', 'FINPIPE', 'CAMS', 'ALKYLAMINE', 'GMDCLTD',  'FSL', 'WESTLIFE', 'ECLERX', 'NUVAMA', 'MAHSEAMLES', 'VGUARD', 
'ERIS', 'SIGNATURE', 'AAVAS', 'JAIBALAJI', 'KSB', 'HBLPOWER', 'RAINBOW', 'HFCL', 'SYRMA', 'RITES', 'EQUITASBNK', 'AKZOINDIA', 'MGL', 'BEML', 'GNFC', 'RAYMOND', 'AETHER', 'KPIL', 'CRAFTSMAN', 'INTELLECT', 'BAJAJELEC', 'ANURAS', 'VTL', 'UJJIVANSFB', 'OLECTRA', 'BIRLACORPN', 'GRINFRA', 'CUB', 'UTIAMC', 'GODFRYPHLP', 'NEWGEN', 'RAILTEL', 'ANANDRATHI', 'BBTC', 'RAJESHEXPO', 'GODREJAGRO', 'GRAPHITE', 'GPIL', 'ALOKINDS', 'ZYDUSWELL', 'JKLAKSHMI', 'AMBER', 'RTNINDIA', 'SPLPETRO', 'NCC', 'MAPMYINDIA', 'DATAPATTNS', 'CANFINHOME', 'CHENNPETRO', 'CAPLIPOINT', 'TTKPRESTIG', 'ELECON', 'PRAJIND', 'CERA', 'SWSOLAR', 'RENUKA', 'EIDPARRY', 'GRSE', 'GALAXYSURF', 'ROUTE', 'ACE', 'GRANULES', 'CEATLTD', 'JKTYRE', 'INGERRAND', 'SCHNEIDER', 'GSFC', 'ENGINERSIN', 'HAPPYFORGE', 'ANANTRAJ', 'JPPOWER', 'KIRLOSENG', 'SBFC', 'LEMONTREE', 'JMFINANCIL', 'PCBL', 'LATENTVIEW', 'SOBHA', 'SAFARI', 'SPARC', 'PRSMJOHNSN', 'NETWORK18', 'ESABINDIA', 'MINDACORP', 'SAPPHIRE', 'USHAMART', 'MMTC', 'PNCINFRA', 'MEDPLUS', 'SARDAEN', 'RPOWER', 'RCF', 'JUBLPHARMA', 'TV18BRDCST', 'BALAMINES', 'MASTEK', 'TECHNOE', 'METROPOLIS', 'TVSSCS', 'KRBL', 'DEEPAKFERT', 'RATEGAIN', 'CCL', 'CAMPUS', 'MAHSCOOTER', 'VIPIND', 'VARROC', 'SURYAROSNI', 'MAHLIFE', 'GAEL', 'RELINFRA', 'BALRAMCHIN', 'IONEXCHANG', 'KFINTECH', 'PGHL', 'HOMEFIRST', 'PRINCEPIPE', 'RESPONIND', 'PTCIL', 'JUBLINGREA', 'KTKBANK', 'MANINFRA', 'GLS', 'SPANDANA', 'ACI', 'INOXINDIA', 'INDIACEM', 'LXCHEM', 'TMB', 'CHEMPLASTS', 'ALLCARGO', 'EMIL', 'SANDUMA', 'MIDHANI', 'TEGA', 'MHRIL', 'SHOPERSTOP', 'DOMS', 'GRAVITA', 'SCI', 'QUESS', 'GPPL', 'TRIVENI', 'EDELWEISS', 'MARKSANS', 'RUSTOMJEE', 'VESUVIUS', 'HEG', 'STARCEMENT', 'PDSL', 'DBREALTY', 'IFCI', 'CSBBANK', 'GMMPFAUDLR', 'EASEMYTRIP', 'SAREGAMA', 'ISGEC', 'KNRCON', 'JLHL', 'INDIGOPNTS', 'LTFOODS', 'KIRLOSBROS', 'RELIGARE', 'JAICORPLTD', 'JKPAPER', 'VIJAYA', 'ROLEXRINGS', 'GARFIBRES', 'ARVIND', 'VRLLOG', 'GREENLAM', 'JUSTDIAL', 'MTARTECH', 'POWERMECH', 'NEULANDLAB', 'GOCOLORS', 'ZENTEC', 'SIS', 'NETWEB', 'VOLTAMP', 'ELECTCAST', 'VAIBHAVGBL', 'BECTORFOOD', 'SUNTECK', 'TEXRAIL', 'RSYSTEMS', 'IWEL', 'FDC', 'REDTAPE', 'EPL', 'SHRIPISTON', 'THOMASCOOK', 'TCI', 'NAVA', 'BLUEJET', 'HNDFDS', 'MOIL', 'NESCO', 'PGEL', 'SYMPHONY', 'WOCKPHARMA', 'ICIL', 'SHAREINDIA', 'JINDWORLD', 'INDIASHLTR', 'GENUSPOWER', 'CMSINFO', 'INFIBEAM', 'STAR', 'NIITMTS', 'TIIL', 'UTKARSHBNK', 'BORORENEW', 'FUSION', 'ASKAUTOLTD', 'ASTRAMICRO', 'JSWHL', 'AVANTIFEED', 'GUJALKALI', 'STLTECH', 'NAZARA', 'GABRIEL', 'SUPRAJIT', 'PTC', 'DBL', 'GHCL', 'RBA', 'SOUTHBANK', 'PARADEEP', 'HGINFRA', 'RAMKY', 'ICRA', 'KESORAMIND', 'SANSERA', 'AURIONPRO', 'ARVINDFASN', 'TEAMLEASE', 'CYIENTDLM', 'AGI', 'HEIDELBERG', 'SENCO', 'KPIGREEN', 'TCIEXP', 'VSTIND', 'DODLA', 'AHLUCONT', 'GREENPANEL', 'GATEWAY', 'ETHOSLTD', 'RAIN', 'HCG', 'ORIENTCEM', 'FEDFINA', 'PRUDENT', 'GOKEX', 'ITDCEM', 'JPASSOCIAT', 'BBOX', 'RALLIS', 'ORIENTELEC', 'RTNPOWER', 'DHANUKA', 'WSTCSTPAPR', 'DBCORP', 'MASFIN', 'WONDERLA', 'LLOYDSENGG', 'KKCL', 'MSTCLTD', 'PATELENG', 'TI', 'SHANTIGEAR', 'PRICOLLTD', 'HGS', 'CHOICEIN', 'PRIVISCL', 'AARTIPHARM', 'MAXESTATES', 'BANCOINDIA', 'NOCIL', 'WELENT', 'AARTIDRUGS', 'NFL', 'JAYNECOIND', 'JAMNAAUTO', 'IIFLSEC', 'PURVA', 'ROSSARI', 'JKIL', 'HEMIPROP', 'GALLANTT', 'HCC', 'MUTHOOTMF', 'DATAMATICS', 'JISLJALEQS', 'ORISSAMINE', 'KALAMANDIR', 'SULA', 'HMAAGRO', 'ADVENZYMES', 'IPL', 'SINDHUTRAD', 'PAISALO', 'AMIORG', 'DCBBANK', 'LAOPALA', 'THANGAMAYL', 'AZAD', 'SHARDACROP', 'TDPOWERSYS', 'SSWL', 'JTLIND', 'EPIGRAL', 'TARC', 'TIMETECHNO', 'FCL', 'VMART', 'RAJRATAN', 'LGBBROSLTD', 'NUCLEUS', 'LUXIND', 'DELTACORP', 'ASHOKA', 'BCG', 'WABAG', 'NEOGEN', 'KIRLPNU', 'JTEKTINDIA', 'SHARDAMOTR', 'ITDC', 'BOROLTD', 'IFBIND', 'ASHAPURMIN', 'SUDARSCHEM', 'HATHWAY', 'SUNFLAG', 'HIKAL', 'TATVA', 'BALMLAWRIE', 'BHARATRAS', 'KOLTEPATIL', 'HINDWAREAP', 'FLAIR', 'SAMHI', 'AVALON', 'HLEGLAS', 'ORCHPHARMA', 'INDOCO', 'HARSHA', 'KDDL', 'BAJAJHIND', 'SANGHVIMOV', 'ESAFSFB', 'SUBROS', 'PILANIINVS', 'GULFOILLUB', 'GREAVESCOT', 'EMUDHRA', 'KIRLOSIND', 'IDEAFORGE', 'UFLEX', 'GANESHHOUC', 'DYNAMATECH', 'MAITHANALL', 
'TVSSRICHAK', 'LANDMARK', 'KSCL', 'NAVNETEDUL', 'THYROCARE', 'TASTYBITE', 'SAKSOFT', 'GMRP_UI', 'DISHTV', 'DALMIASUG', 'CARTRADE', 'NILKAMAL', 'DCXINDIA', 'POLYPLEX', 'SAGCEM', 'SHALBY', 'SANGHIIND', 'GRWRHITECH', 'VSTTILLERS', 'SUNDARMHLD', 'NRBBEARING', 'YATHARTH', 'AUTOAXLES', 'BANARISUG', 'GENSOL', 'PFOCUS', 'BOMDYEING', 'SBCL', 'BAJAJCON', 'INNOVACAP', 'INOXGREEN', 'SOMANYCERA', 'SUNCLAY', 'GUFICBIO', 'MOLDTKPAC', 'JCHAC', 'DIVGIITTS', 'PRAKASH', 'APOLLO', 'SANDHAR', 'GREENPLY', 'CIGNITITEC', 'WENDT', 'STYLAMIND', 'SWARAJENG', 'MPSLTD', 'IFGLEXPOR', 'KINGFA', 'DREAMFOLKS', 'SHILPAMED', 'SEPC', 'UNICHEMLAB', 'MUKANDLTD', 'IMAGICAA', 'VENUSPIPES', 'SEQUENT', 'CARERATING', 'PGIL', 'HERITGFOOD', 'PARAS', 'TARSONS', 'FIEMIND', 'JINDALPOLY', 'BSHSL', 'PSPPROJECT', 'VENKEYS', 'MAHLOG', 'BBL', 'PARAGMILK', 'ZAGGLE', 'IOLCP', 'ASHIANA', 'ANUP', 'DEN', 'PFS', 'IMFA', 'APOLLOPIPE', 
'VPRPL', 'DCAL', 'GANDHAR', 'GOODLUCK', 'APCOTEXIND', 'SEAMECLTD', 'OPTIEMUS', 'LUMAXTECH', 'SATIN', 'GIPCL', 'DOLLAR', 'BARBEQUE', 'UNIPARTS', 'VINDHYATEL', 'MBAPL', 'GOCLCORP', 'DIAMONDYD', 'CONFIPET', 'STYRENIX', 'EVEREADY', 'SUPRIYA', 'GLOBUSSPR', 'UGROCAP', 'BEPL', 'MAYURUNIQ', 'MOREPENLAB', 'IKIO', 'HMT', 'REPCOHOME', 'MUFIN', 'AXISCADES', 'FOSECOIND', 'ARTEMISMED', 'ANDHRAPAP', 'SOTL', 'SIYSIL', 'HINDOILEXP', 'HONDAPOWER', 'INDIAGLYCO', 'PRECAM', 'EMSLIMITED', 'SKIPPER', 'DHANI', 'MMFL', 'ALEMBICLTD', 'LUMAXIND', 'VISHNU', 'CAMLINFINE', 'YATRA', 'KRSNAA', 'PITTIENG', 'MANORAMA', 'TIRUMALCHM', 'UDS', 'SIRCA', 'BFUTILITIE', 'RISHABH', 'IRMENERGY', 'SESHAPAPER', 'RPGLIFE', 'SDBL', 'ADFFOODS', 'ORIENTHOT', 'PCJEWELLER', 'FILATEX', '63MOONS', 'CARYSIL', 'FINOPB', 'EVERESTIND', 'RPSGVENT', 'HUHTAMAKI', 'PRECWIRE', 'ASTEC', 'GTPL', 'XPROINDIA', 'GANECOS', 'SADHNANIQ', 'GREENPOWER', 'JINDRILL', 'RUPA', 'SANGAMIND', 'ARMANFIN', 'ATFL', 'HIL', 'MTNL', 'KSL', 'ACCELYA', 'SASKEN', 'SHRIRAMPPS', 'INDOSTAR', 'SALASAR', 'BHARATWIRE', 'VIDHIING', 'TNPL', 'PARACABLES', 'TCPLPACK', 'KIRIINDUS', 'ADORWELD', 'MANGLMCEM', 'SPECTRUM', 'JAGRAN', 'RIIL', 'EXPLEOSOL', 'SHK', 'BFINVEST', 'PANAMAPET', 'VAKRANGEE', 'FMGOETZE', 'AEROFLEX', 'TTKHLTCARE', 'INSECTICID', 'VERANDA', 'KCP', 'THEJO', 'MOL', 'CANTABIL', 'THEMISMED', 'MARATHON', 'ARVSMART', 'QUICKHEAL', 'SMLISUZU', 'SJS', 'GNA', 'SUBEXLTD', 'DPSCLTD', 'RAMCOIND', 'SHAKTIPUMP', 'JASH', 'MUFTI', 'GEOJITFSL', 'YASHO', 'BUTTERFLY', 'CAPACITE', 'TALBROAUTO', 'GOLDIAM', 'GOKULAGRO', 'RANEHOLDIN', 'VADILALIND', 'NITINSPIN', 'NELCO', 'MADRASFERT', 'VSSL', 'HLVLTD', 'RAMASTEEL', 'ROSSELLIND', 'PIXTRANS', '5PAISA', 'SUVEN', 'UNITECH', 'CENTUM', 'PNBGILTS', 'AMRUTANJAN', 'BCLIND', 'MANINDS', 'HARIOMPIPE', 'PREMEXPLN', 'WHEELS', 'NDTV', 'DHAMPURSUG', 'PENIND', 'DREDGECORP', 'DCW', 'SPCENET', 'NSIL', 'GTLINFRA', 'UNIVCABLES', 'SURYODAY', 'SICALLOG', 'HIMATSEIDE', 'DEEPINDS', 'FAIRCHEMOR', 'IGARASHI', 'SERVOTECH', 'ACLGATI', 'CONTROLPR', 'SHANKARA', 'PUNJABCHEM', 'COSMOFIRST', 'DWARKESH', 'HPL', 'BHAGCHEM', 'AHL', 'GVKPIL', 'NPST', 'HERANBA', 'INDRAMEDCO', 'SIGACHI', 'HITECH', 'ATULAUTO', 'SPIC', 'AJMERA', 'MVGJL', 'GENESYS', 'NAVKARCORP', 'VASCONEQ', 'GEPIL', 'UTTAMSUGAR', 'SHAILY', 'NIITLTD', 'APTECHT', 'SPAL', 'BAJEL', 'KUANTUM', 'ANDHRSUGAR', 'KRISHANA', 'POKARNA', 'CUPID', 'KABRAEXTRU', 'KITEX', 'MONARCH', 'STOVEKRAFT', 'SURAJEST', 'KOKUYOCMLN', 'JSLL', 'MONTECARLO', 'OMINFRAL', 'PENINLAND', 'DPABHUSHAN', 'NACLIND', 'MANGCHEFER', 'BLKASHYAP', 'KICL', 'EKC', 'JITFINFRA', 'IGPL', 'HARDWYN', 'TAJGVK', 'SYNCOMF', 'BETA', 'EIHAHOTELS', 'SATIA', 'ONWARDTEC', 'AVTNPL', 'ALICON', 'VALIANTORG', 'AGARIND', 'NGLFINE', 'SUMMITSEC', 'KSOLVES', 'SHREDIGCEM', 'NELCAST', 'OMAXE', 'HEUBACHIND', 'AWHCL', 'MANALIPETC', 'INDORAMA', 'COFFEEDAY', 'OAL', 'AVADHSUGAR', 'DCMSRIND', 'TEXINFRA', 'ROTO', 'RML', 'GULPOLY', 'REFEX', 'MARINE', 'RAMRAT', 'SATINDLTD', 'BLISSGVS', 'SASTASUNDR', 'SOLARA', 'ATL', 'MATRIMONY', 'STERTOOLS', 'GMBREW', 'SHALPAINTS', 'CLSEL', 'INDIANHUME', 'REPRO', 'TVTODAY', 'IMPAL', 'HESTERBIO', 'ZOTA', 'STEELCAS', 'JYOTISTRUC', 'INDNIPPON', 'LINCOLN', 'XCHANGING', 'CENTRUM', 'RICOAUTO', 'FOCUS', 'KOPRAN', 'GICHSGFIN', 'BIGBLOC', 'SHIVALIK', 'JAYBARMARU', 'DLINKINDIA', 'TFCILTD', 'EXCELINDUS', 'INNOVANA', 'ONMOBILE', 'GRMOVER', 'AGSTRA', 'TRACXN', 'TREL', 'HERCULES', 'REMUS', 'ARIHANTSUP', 'DVL', 'UNIENTER', 'LIKHITHA', 'GANESHBE', 'SKYGOLD', 'FAZE3Q', 'KAMOPAINTS', 'CHEMCON', 'SPORTKING', 'INFOBEAN', 'RAJRILTD', 'CREATIVE', 'GFLLIMITED', 'CONSOFINVT', 'SMCGLOBAL', 'SNOWMAN', 'NINSYS', 'ASIANENE', 'MKPL', 'SBGLP', 'GIRIRAJ', 'BODALCHEM', 'RUSHIL', 'V2RETAIL', 'VISHNUINFR', 'BAJAJHCARE', 'CSLFINANCE', 'RAMCOSYS', 'RSWM', 'PANACEABIO', 'SKMEGGPROD', 'NAHARSPING', 'NCLIND', 'DBOL', 'JAGSNPHARM', 'ACL', 'SMSPHARMA', 'VHL', 'LINC', 'NDRAUTO', 'ONEPOINT', 'DENTALKART', 'RGL', 'KAMDHENU', 'STEELXIND', 'AMBIKCO', 'SPENCERS', 'ICEMAKE', 'KELLTONTEC', 
'MOTISONS', 'SRHHYPOLTD', 'MAGADSUGAR', 'SCHAND', 'GPTINFRA', 'ASIANTILES', 'DYCL', 'SUTLEJTEX', 'WEBELSOLAR', 'E2E', 'RADIANTCMS', 'PPL', 'CENTENKA', 'GANDHITUBE', 'ZEEMEDIA', 'EIMCOELECO', 'YUKEN', 'MSPL', 'UGARSUGAR', 'HIRECT', 'AMNPLST', 'HPAL', 'SPECIALITY', 'ORIENTPPR', 'SREEL', 'JUBLINDS', 'TRU', 'TNPETRO', 'VIMTALABS', 'ORIANA', 'DPWIRES', 'KERNEX', 'WINDLAS', 'VINYAS', 
'DHARMAJ', 'SILVERTUC', 'GKWLIMITED', 'INDOAMIN', 'MUNJALAU', 'ASALCBR', 'ENIL', 'BLAL', 'CHEVIOT', 'FOODSIN', 'ROHLTD', 'WALCHANNAG', 'MANAKSIA', 'PAKKA', 'BIRLACABLE', 'HITECHGEAR', 'KOTHARIPET', 'SAKAR', 'KOTYARK', 'SANDESH', 'TBZ', 'BCONCEPTS', 'HEXATRADEX', 'OCCL', 'VINYLINDIA', 'DMCC', 'STCINDIA', '3IINFOLTD', 'CREST', 'DENORA', 'SWELECTES', 'ZUARI', 'DSSL', 'DECCANCE', 'MOLDTECH', 'RUBYMILLS', 'DHANBANK', 'URJA', 'NAGAFERT', 'MAANALU', 'MENONBE', 'SUKHJITS', 'PLASTIBLEN', 'MEDICAMEQ', 'GSLSU', 'ADSL', 'VALIANTLAB', 'BALAJITELE', 'JAYAGROGN', 'SELAN', 'MICEL', 'VISAKAIND', 'ESTER', 'EMKAYTOOLS', 'KECL', 'ELIN', 'INDOBORAX', 'ARIHANTCAP', 'DHUNINV', 'SEMAC', 'NECLIFE', 'ELDEHSG', 'EMAMIPAP', 'BHAGERIA', 'VLSFINANCE', 'VIKASLIFE', 'SHREEPUSHK', 'FCSSOFT', 'PYRAMID', 'CHEMBOND', 'INDOTECH', 'MAXIND', 'APEX', 'MEDICO', 'BGRENERGY', 'BASILIC', 'MALLCOM', 'NRAIL', 'SALZERELEC', 'KHAICHEM', 'OSWALGREEN', 'HMVL', 'AXITA', 'HCL_INSYS', 'HINDCOMPOS', 'CELLECOR', 'GHCLTEXTIL', 'ASAL', 'KAMATHOTEL', 'TVSELECT', 'ARROWGREEN', 'JETAIRWAYS', 'RBL', 'RITCO', 'IRISDOREME', 'ESSARSHPNG', 'VERTOZ', 'DIGISPICE', 'LOKESHMACH', 'GRPLTD', 'JPOLYINVST', 'HUBTOWN', 'VLEGOV', 'KHADIM', 'SBC', 'MIRZAINT', 'APCL',  '20MICRONS', 'RACE', 'MUTHOOTCAP', 'ACCENTMIC', 'ORIENTCER', 'JINDALPHOT', 'INDSWFTLAB', 'GLOBAL', 'KRISHIVAL', 'THEINVEST', 'MACPOWER', 'KILITCH', 'STEL', 'MINDTECK', 'ORIENTBELL', 'HTMEDIA', 'OSIAHYPER', 'NIPPOBATRY', 'ZUARIIND', 'BIRLAMONEY', 'MUNJALSHOW', 'POCL', 'RADIOCITY', 'KANORICHEM', 'INTLCONV', 'AARTISURF', 'BBTCL', 'CYBERTECH', 'COOLCAPS', 'ZIMLAB', 'RATNAVEER', 'ALBERTDAVD', 'BEDMUTHA', 'NAHARPOLY', 'PRIMESECU', 'KRITI', 'WINDMACHIN', 'UNIDT', 'NAHARINDUS', 'CLEDUCATE', 'PTL', 'VENUSREM', 'WEL', 'WSI', 'DIAMINESQ', 'GOKUL', 'SARVESHWAR', 'MMP', 'RADHIKAJWE', 'ORICONENT', 'MAZDA', 'CHEMFAB', 'SAHANA', 'GOACARBON', 'ANNAPURNA', 'PROZONER', 'ASMS', 'EXXARO', 'DONEAR', 'DOLPHIN', 'AUTOIND', 'NAHARCAP', 'TIRUPATI', 'PHANTOMFX', 'PAVNAIND', 'MEGASOFT', 'BANSWRAS', 'GENUSPAPER', 'PDMJEPAPER', 'NDLVENTURE', 'SIGMA', 'ALLETEC', 'GEECEE', 'ORBTEXP', 'VARDHACRLC', 'GEEKAYWIRE', 'ADVANIHOTR', 'LIBERTSHOE', 'MBLINFRA', 'SARLAPOLY', 'SOUTHWEST', 'UNIVPHOTO', 'VIKASECO', 'SHIVAMAUTO', 'EUROBOND', 'PARSVNATH', 'NEWJAISA', 'KRISHNADEF', 'RBZJEWEL', 'IFBAGRO', 'SIMPLEXINF', 'SPMLINFRA', 'WEALTH', 'SILINV', 'NBIFIN', 'OSWALAGRO', 'MODISONLTD', 'DICIND', 'SGIL', 'SAHYADRI', 'AVG', 'ASIANHOTNR', 'BALAXI', 'RPPINFRA', 'KAYA', 'CINELINE', 'HITECHCORP', 'PLAZACABLE', 'SHYAMCENT', 'SHEMAROO', 'OSWALSEEDS', 'GOLDTECH', 'UFO', 'KORE', 'ESFL', 'LORDSCHLO', 'KOTARISUG', 'KRITINUT', 'NURECA', 'SHIVAUM', 'BPL', 'SAKUMA', 'TRIGYN', 'WANBURY', 'EMAMIREAL', 'BRNL', 'DUGLOBAL', 'ALANKIT', 'NRL', 'BIL', 'LYKALABS', 'IITL', 'IL_FSENGG', 'GOLDSTAR', 'KCPSUGIND', 'TPLPLASTEH', 'PODDARMENT', 'CLOUD', 'HIGREEN', 'CRAYONS', 'RUCHIRA', 'SHREERAMA', 'FOCE', 'VMARCIND', 'NATHBIOGEN', 'APOLSINHOT', 'VINSYS', 'EIFFL', 'REMSONSIND', 'NDL', 'SAAKSHI', 'SYSTANGO', 'VIPCLOTHNG', 'MAWANASUG', 'RAMAPHO', 'BROOKS', 'TIL', 'KOTHARIPRO', 'PVP', 'RBMINFRA', 'ANMOL', 'IVC', 'SADBHAV', 'AURUM', 'KODYTECH', 'MEGASTAR', 'MAHEPC', 'MIRCELECTR', 'RANASUG', 
'BEWLTD', 'SRGHFL', 'DRONE', 'STARPAPER', 'DYNPRO', 'ASAHISONG', 'DEVIT', 'SHREYANIND', 'INSPIRISYS', 'URAVI', 'NILAINFRA', 'AYMSYNTEX', 'REPL', 'ROXHITECH', 'PRAXIS', 'PONNIERODE', 'HINDMOTORS', 'SKP', 'SCPL', 'EMKAY', 'SMLT', 'STARTECK', 'COASTCORP', 'TIPSFILMS', 'SOLEX', 'PREMIERPOL', 'AIRAN', 'CAREERP', 'SINTERCOM', 'PROV', 'SAKHTISUG', 'TAKE', 'IZMO', 'BHAGYANGR', 'KNAGRI', 'PASUPTAC', 'PRECOT', 'PPAP', 'ZODIACLOTH', 'MHLXMIRU', 'SAH', 'INFINIUM', 'ASHIMASYN', 'SHERA', 'RVHL', 'LOYALTEX', 'UCAL', 'DCMNVL', 'HARRMALAYA', 'ESSENTIA', 'GSS', 'LGHL', 'MANORG', 'MANAKSTEEL', 'BASML', 'VISHWARAJ', 'MURUDCERA', 'JAYSREETEA', 'PILITA', 'GUJAPOLLO', 'ELECTHERM', 'DELPHIFX', 'ABAN', 'TEMBO', 'INDTERRAIN', 'SURANI', 'KRITIKA', 'HINDCON', 'PRITIKAUTO', 'AARON', 'MWL', 'VIRINCHI', 'RAJMET', 'ZODIAC', 'MARALOVER', 'ELGIRUBCO', 'KMSUGAR', 'ZEAL', 'USASEEDS', 'RAJTV', 'MCLEODRUSS', 'PARAGON', 'PRITI', 'GULFPETRO', 'TRF', 'MEP', 'EQUIPPP', 'MANOMAY', 'SUPERHOUSE', 'SECL', 'GOYALSALT', 'EFORCE', 'NECCLTD', 'PROPEQUITY', 'BAIDFIN', 'FROG', 'KRISHCA', 'ARIES', 'PAR', 'SELMC', 'SUNDRMBRAK', 'RANEENGINE', 'SUPREMEPWR', 'RAMANEWS', 'KAPSTON', 
'IRIS', 'KANPRPLA', 'SEJALLTD', 'TARACHAND', 'GINNIFILA', 'RUCHINFRA', 'SVLL', 'BTML', 'AHLEAST', 'SPECTSTM', 'RHL', 'LAL', 'BYKE', 'COMPUSOFT', 'AKSHARCHEM', 'SARTELE', 'RPPL', 'INTENTECH', 'ALMONDZ', 'MGEL', 'NDGL', 'HILTON', 'DUCON', 'SJLOGISTIC', 'CANARYS', 'GILLANDERS', 'MAHESHWARI', 'AURDIS', 'SOFTTECH', 'GREENCHEF', 'CORALFINAC', 'DTIL', 'AARVI', 'IVP', 'PALREDTEC', 'EROSMEDIA', 'INDOTHAI', 'QMSMEDI', 'NITCO', 'WELINV', 'MAGNUM', 'GENCON', 'ATAM', 'CCHHL', 'GIRRESORTS', 'RELCHEMQ', 'ARSHIYA', 'VITAL', 'KEL', 'LLOYDS', 'CHAVDA', 'ASCOM', 'MADHAVBAUG', 'VETO', 'SHIGAN', 'MOS', 'INDOWIND', 'SUVIDHAA', 'SWASTIK', 
'INVENTURE', 'ALPA', 'BAFNAPH', 'BSL', 'INFOLLION', 'LOVABLE', 'TTL', 'TEXMOPIPES', 'ZEELEARN', 'USK', 'TREJHARA', 'MAHAPEXLTD', 'DCI', 'DIGIKORE', 'SURANAT_P', 'MODIRUBBER', 'IEL', 'TOTAL', 'EFACTOR', 'VIPULLTD', 'RHFL', 'SALSTEEL', 'A2ZINFRA', 'LATTEYS', 'DENEERS', 'SPLIL', 'KDL', 'JOCIL', 'TARMAT', 'NOIDATOLL', 'ATLANTAA', 'UNITEDPOLY', 'UNIHEALTH', 'AKSHOPTFBR', 'SRIVASAVI', 'ARCHIDPLY', 'AIROLAM', 'ROCKINGDCE', 'ASPINWALL', 'VAISHALI', 'KAKATCEM', 'KBCGLOBAL', 'ARVEE', 'AVONMORE', 'VISESHINFO', 'SIGIND', 'JMA', 'AKI', 'NILASPACES', 'FELIX', 'MANAKCOAT', 'SHIVATEX', 'RAJSREESUG', 'EMMBI', 'GLOBALVECT', 'BAHETI', 'TOUCHWOOD', 'WEIZMANIND', 'SHAH', 'SMARTLINK', 'DRCSYSTEMS', 'UMAEXPORTS', 'SHRITECH', 'PASHUPATI', 'BEARDSELL', 'NIRMAN', 'ALPHAGEO', 'ISFT', 'TECHLABS', 'BHARATGEAR', 'NIRAJ', 'GVPTECH', 'CAPTRUST', 'ARHAM', 'RKEC', 'BAGFILMS', 'MUKTAARTS', 'LOTUSEYE', 'TRANSTEEL', 'DANGEE', 'DYNAMIC', 'WORTH', 'AHLADA', 'SIKKO', 'DUCOL', 'KOHINOOR', 'FCONSUMER', 'KREBSBIO', 'INDBANK', 'PRAKASHSTL', 'XELPMOC', 'AMJLAND', 'DJML', 'UMANGDAIRY', 'JHS', 'SURANASOL', 'CADSYS', 'SADBHIN', 'RILINFRA', 'URBAN', 'LAMBODHARA', 'UNITEDTEA', 'SECURKLOUD', 'MANAKALUCO', 'IL_FSTRANS', 'SMSLIFE', 'THOMASCOTT', 'INDIANCARD', 'SUMIT', 'BALPHARMA', 'PARTYCRUS', 'PANSARI', 'MADHUSUDAN', 'INCREDIBLE', 'LAGNAM', 'MANGALAM', 'KARNIKA', 'TIRUPATIFL', 'SIL', 'VARDMNPOLY', 'SALONA', '3RDROCK', 'AMDIND', 'YUDIZ', 'SWARAJ', 'FIDEL', 'CENTEXT', 'ASTRON', 'RSSOFTWARE', 'LASA', 'KALYANIFRG', 'RMDRIP', 'DCM', 'CMNL', 'MOTOGENFIN', 
'CTE', 'IPSL', 'CORDSCABLE', 'PRAENG', 'ACCURACY', 'ANLON', 'AARTECH', 'SUNDARAM', 'SONAMLTD', 'SURYALAXMI', 'GTL', 'ARTNIRMAN', 'GOYALALUM', 'ALKALI', 'OMAXAUTO', 'FLEXITUFF', 'SHRADHA', 'MAHASTEEL', 'GOLDKART', 'TAINWALCHM', 'ANIKINDS', 'PULZ', 'WIPL', 'SSFL', 'SUPREMEINF', 'ABCOTS', 'JAINAM', 'OILCOUNTUB', 'SECMARK', 'SOTAC', 'GRAPHISAD', 'PIONEEREMB', 'GICL', 'AAREYDRUGS', 'ENERGYDEV', 'SHAHALLOYS', 'MAL', 'PATINTLOG', 'SVPGLOB', 'PARIN', 'SHREEOSFM', 'OBCL', 'MITCON', 'GANGESSECU', 'GTECJAINX', 'DOLLEX', 'MHHL', 'SIMBHALS', 'NITIRAJ', 'TIMESGTY', 'VELS', 'MDL', 'CROWN', 'DIL', 'HPIL', 'BLBLIMITED', 'PALASHSECU', 'UNIVASTU', 'DBSTOCKBRO', 'PRUDMOULI', 'AAKASH', 'AGRITECH', 'DAMODARIND', 'QUICKTOUCH', 'S_SPOWER', 'BANKA', 'BVCL', 'ONDOOR', 'TOKYOPLAST', 'ZENITHSTL', 'HOMESFY', 'SYNOPTICS', 'AVROIND', 'STEELCITY', 'BABAFP', 'HISARMETAL', 'MCON', 'AKSHAR', 'DGCONTENT', 'RCDL', 'MRO_TEK', 'SOMICONVEY', 'GRCL', 'AAATECH', 'YAARI', 'VIVIANA', 'GROBTEA', 'VERTEXPLUS', 'ARABIAN', 'MCL', 'MARSHALL', 'NIBL', 'KHFM', 'ARIHANTACA', 'DELTAMAGNT', 'PRESSTONIC', 'SAMPANN', 'PKTEA', 'BHANDARI', 'LPDC', 'HOLMARC', 'LEMERITE', 'MBECL', 'INDSWFTLTD', 'MAGSON', 'CINEVISTA', 'PANACHE', 'ARCHIES', 'FIBERWEB', 'REGENCERAM', 'TPHQ', 'SHEETAL', 'AATMAJ', 'SETCO', 'CELEBRITY', 'PROLIFE', 'HECPROJECT', 'MARCO', 'GLOBALPET', 'HOVS', 'CUBEXTUB', 'AUSOMENT', 'KARMAENG', 'AGROPHOS', 'DHRUV', 'WEWIN', 
'PENTAGON', 'ATALREAL', 'AUROIMPEX', 'TREEHOUSE', 'VINNY', 'BIOFILCHEM', 'GOLDENTOBC', 'RELIABLE', 'MONOPHARMA', 'ZENITHEXPO', 
'VASWANI', 'ASHOKAMET', 'INSPIRE', 'PRITIKA', 'KEYFINSERV', 'LEXUS', 'CPS', 'CELLPOINT', 'PODDARHOUS', 'MORARJEE', 'ORIENTLTD', 'MAITREYA', 'PRAMARA', 'SHIVAMILLS', 'CEREBRAINT', 'NAGREEKEXP', 'MICROPRO', 'MAHICKRA', 'TRIDHYA', 'CLSL', 'SECURCRED', 'VIAZ', 'AKG', 'TERASOFT', 'TAPIFRUIT', 'AVSL', 'COMPINFO', 'SCML', 'JAIPURKURT', 'SHRENIK', 'GSTL', 'SAMBHAAV', 'SHUBHLAXMI', 'VINEETLAB', 'AROGRANITE', 'MOKSH', 'KANANIIND', 'PARASPETRO', 'ICDSLTD', 'SOMATEX', 'PNC', 'ACSAL', 'ROML', 'UCL', 'BMETRICS', 'GANGAFORGE', 'SITINET', 'MANUGRAPH', 'ANKITMETAL', 'MALUPAPER', 'SHANTHALA', 'AARVEEDEN', 'UWCSL', 'BANG', 'SIDDHIKA', 'SERVICE', 
'PIGL', 'MAKS', 'REXPIPES', 'BANARBEADS', 'AISL', 'NGIL', 'AKASH', 'ISHAN', 'TFL', 'DNAMEDIA', 'CBAZAAR', 'GLOBE', 'COMMITTED', 'JETFREIGHT', 'UMA', 'YCCL', 'BDR', 'PRECISION', 'MASTER', 'FLFL', 'DKEGL', 'EXCEL', 'DESTINY', 'AJOONI', 'SANGANI', 'WOMANCART', 'MADHAV', 'LFIC', 'BURNPUR', 'JETKNIT', 'SEYAIND', 'MILTON', 'PEARLPOLY', 'VSCL', 'HBSL', 'OMFURN', 'ADL', 'ABMINTLLTD', 'AMBICAAGAR', 'KEEPLEARN', 'MADHUCON', 'AGNI', 'BINANIIND', 'RKDL', 'CMRSL', 'SUULD', 'CYBERMEDIA', 'TCLCONS', 'INDIFRA', 'TIMESCAN', 'SANGINITA', 'LIBAS', '3PLAND', 'FSC', 'SRPL', 'SEL', 'NIDAN', 'VEEKAYEM', 'KONTOR', 'SUPERSPIN', 'SAGARDEEP', 'JFLLIFE', 
'HAVISHA', 'SONUINFRA', 'EDUCOMP', 'TGBHOTELS', 'ARISTO', 'ADROITINFO', 'SGL', 'ASLIND', 'GODHA', 'DIACABS', 'MARINETRAN', 'LAXMICOT', 'JIWANRAM', 'PATTECH', 'COUNCODOS', 'NEXTMEDIA', 'TNTELE', 'AGUL', 'ACEINTEG', 'BALKRISHNA', 'AGARWALFT', 'KKVAPOW', 'AMEYA', 'KHANDSE', 'GATECH', 'WALPAR', 'TECILCHEM', 'WILLAMAGOR', 'BOHRAIND', 'SHAIVAL', 'SAHAJ', 'FMNL', 'MEGAFLEX', '21STCENMGM', 'KSHITIJPOL', 'HEADSUP', 'NKIND', 'ROLLT', 'PLADAINFO', 'VILINBIO', 'VIVIDHA', 'KRIDHANINF', 'GUJRAFFIA', 'SABAR', 'QUADPRO', 'NARMADA', 'INFOMEDIA', 'IMPEXFERRO', 'CONTI', 'QFIL', 'MINDPOOL', 'KAVVERITEL', 'KAUSHALYA', 'MITTAL', 'UNIINFO', 'MTEDUCARE', 'LCCINFOTEC', 'KHAITANLTD', 'CALSOFT', 'SILGO', 'SUNREST', 'MOXSH', 'RICHA', 'ORIENTALTL', 'HYBRIDFIN', 'VCL', 'RITEZONE', 
'SUPREMEENG', 'VERA', 'LRRPL', 'OLIL', 'WINSOME', 'MOHITIND', 'MASKINVEST', 'ANTGRAPHIC', 'ONELIFECAP', 'TECHIN', 'MPTODAY', 'SAROJA', 'LYPSAGEMS', 'SHANTI', 'NAGREEKCAP', 'GRETEX', 'TIJARIA', 'OMKARCHEM', 'VIVO', 'SILLYMONKS', 'SPRL', 'AILIMITED', 'DIGJAMLMTD', 'UMESLTD', 'VIJIFIN', 'KANDARP', 'TVVISION', 'KCK', 'AMIABLE', 'JAKHARIA', 'ARENTERP', 'BLUECHIP', 'GLFL', 
'NORBTEAEXP', 'TRANSWIND', 'DRL', 'SMVD', 'EUROTEXIND', 'SHYAMTEL', 'RADAAN', 'TARAPUR', 'MANAV', 'PREMIER', 'BKMINDST', 'ACCORD', 'ALPSINDUS', 'DCMFINSERV', 'SANCO', 'AHIMSA', 'CREATIVEYE', 'JALAN', 'UNIVAFOODS', 'BLUECOAST', 'SABEVENTS', 'MELSTAR', 'LAKPRE', 'VASA', 'ANSALAPI', 'ARSSINFRA', 'BGLOBAL', 'CCCL', 'CMICABLES', 'FEL', 'GANGOTRI', 'GAYAPROJ', 'GAYAHWS', 'GFSTEELS', 'GOENKA', 'HINDNATGLS', 'HDIL', 'MODTHREAD', 'NTL', 'ORTEL', 'QUINTEGRA', 'RAJVIR', 'RCOM', 'ROLTA', 'SANWARIA', 'SETUINFRA', 'SKIL', 'SUMEETINDS', 'TCIFINANCE', 'VISASTEEL']



from_date = '2024-08-18' 

to_date ='2024-12-18'

filtered_data= []


# Convert to Heikin-Ashi
def convert_to_heikin_ashi(df):
    ha_df = df.copy()
    # Calculate Heikin-Ashi Close
    ha_df["ha_close"] = (df["open"] + df["high"] + df["low"] + df["close"]) / 4

    # Initialize Heikin-Ashi Open with the first row
    ha_df["ha_open"] = 0.0
    ha_df.loc[0, "ha_open"] = (df.loc[0, "open"] + df.loc[0, "close"]) / 2

    # Calculate Heikin-Ashi Open, High, and Low
    for i in range(1, len(df)):
        ha_df.loc[i, "ha_open"] = (ha_df.loc[i - 1, "ha_open"] + ha_df.loc[i - 1, "ha_close"]) / 2

    ha_df["ha_high"] = ha_df[["high", "ha_open", "ha_close"]].max(axis=1)
    ha_df["ha_low"] = ha_df[["low", "ha_open", "ha_close"]].min(axis=1)
    ha_df["volume"] = df['volume']


    # Return only Heikin-Ashi columns
    return ha_df[["ha_open", "ha_high", "ha_low", "ha_close"]]

# Convert to Heikin-Ashi while retaining existing columns
def convert_to_heikin_ashi_with_original_columns(df):
    ha_df = df.copy()

    # Calculate Heikin-Ashi Close
    ha_df["ha_close"] = (df["open"] + df["high"] + df["low"] + df["close"]) / 4

    # Initialize Heikin-Ashi Open with the first row
    ha_df["ha_open"] = 0.0
    ha_df.loc[0, "ha_open"] = (df.loc[0, "open"] + df.loc[0, "close"]) / 2

    # Calculate Heikin-Ashi Open, High, and Low
    for i in range(1, len(df)):
        ha_df.loc[i, "ha_open"] = (ha_df.loc[i - 1, "ha_open"] + ha_df.loc[i - 1, "ha_close"]) / 2

    ha_df["ha_high"] = ha_df[["high", "ha_open", "ha_close"]].max(axis=1)
    ha_df["ha_low"] = ha_df[["low", "ha_open", "ha_close"]].min(axis=1)

    # Return the full DataFrame (original + Heikin-Ashi columns)
    return ha_df


for symbol in symbols:
    # Fetch historical data
    try:
        data = kite.historical_data(    
            instrument_token=kite.ltp("NSE:" + symbol)["NSE:" + symbol]["instrument_token"],
            from_date=from_date,  # Adjust the date range
            to_date=to_date,
            interval=interval,
        )
        df = pd.DataFrame(data)
        # df['EMA9'] = df['close'].ewm(span=9, adjust=False).mean()
        # df['EMA20'] = df['close'].ewm(span=20, adjust=False).mean()   
        # print(df)
        # Convert your OHLC data to Heikin-Ashi
        # heikin_ashi_df = convert_to_heikin_ashi(df)
        heikin_ashi_full_df = convert_to_heikin_ashi_with_original_columns(df)
        # print(heikin_ashi_full_df)
        last_two_rows = heikin_ashi_full_df.tail(2)
        # print(last_two_rows)
#
        current_day = last_two_rows.tail(1)
        previous_day = last_two_rows.head(1)
      
        if current_day["ha_open"].iloc[0] == current_day["ha_high"].iloc[0]:
            if previous_day["ha_open"].iloc[0] < previous_day["ha_close"].iloc[0]:

                print(symbol)
            # pass

    except Exception as e:
        pass
        # print(f"Error fetching historical data for {symbol}: {str(e)}")


for i in filtered_data:
    print(i)
